# fly.toml app configuration file generated for hadi-soroush on 2023-04-19T17:01:07+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "hadi-soroush"
primary_region = "ams"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  image = "mhsoroush/datingapp:latest"

[env]
  ASPNETCORE_URLS="http://+:8080"
  CloudinarySettings__CloudName="dmuahge7y"
  CloudinarySettings__ApiKey="496498249662127"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
